### PR TITLE
JWWEB-289: Add X-Frame-Options to nginx config

### PR DESCRIPTION
**Pull request by stcherenkov**

### CODE REVIEW

**Comment by soar** [comment]
Don't forget to check that this value won't be rewritten and will be available through all layers of balancing and proxying @jibrelnetwork/qa

**Comment by soar** [comment]
Or we can set this header globally for all projects, so we don't need to change each config in each microservice

**Comment by stcherenkov** [comment]
@soar not sure if we need to set this for every project.

**Comment by stcherenkov** [comment]
Fixed via infrastructure

**Pull request closed without merging**
