### PR TITLE
Implement wrappers for web workers

### PR DESCRIPTION
**Pull request by IViol**
# PromiseWorker
### executeTask
*Sends message to worker and waits for response*
#### Input
```
  {
    payload,
    taskName,
    transfer,
    errorMessage,
  }: PromiseWorkerTaskPayload
```
#### Output
```
Promise, that will be resolved/rejected once worker response is returned
```
### terminate
*Terminates worker, removes listeners, cleans tasks queue*
#### Input
```
null
```
#### Output
```
null
```
### restart
*Terminates old worker and starts new another one*
#### Input
```
newWorker: Object
```
#### Output
```
null
```

## Example of usage
*worker.js*
```
self.onmessage = (msg) => {
  const {
    taskId,
    payload,
    taskName,
  } = msg.data

  switch(taskName) {
    case 'some task name': {
      // process payload

      self.postMessage({
        taskId,
        payload: 'some payload here' || { /* could be object */ }
      })
    }

    case 'some task name': {
      try {
        // process payload, that could throw

        self.postMessage({ /* on success */ })
      } catch (err) {
        self.postMessage({
          taskId, // very important to send taskId back
          error: true, // very important to set 'error' attribute to true
          payload: { // currently all errors from workers must have such format
            stack: err.stack,
            message: err.message,
          },
        })
      }
    }

    default:
      break
  }
}
```
**Note**: `taskId` in response message of worker is the only way how we can determine "for what task this result is" - it's the most important part in implementation of worker.

*main.js*
```
import Worker from './worker.js'
import PromiseWorker from './PromiseWorker'

const worker = new Worker()
const promiseWorker = new PromiseWorker(worker)

const taskData = {
  taskName: 'some task name',
  errorMessage: 'optional timeout error message',
  payload: 'some payload that will be used inside worker to process task',
  transfer: 'optional array of Transferable objects to transfer ownership of (second argument of worker postMessage method)',
}

promiseWorker
  .executeTask(taskData)
  .then(result => { /* handle worker response */ })
  .catch(err => { /* handle error */ })
```

For live example please check two reverted commits:
- d599baa
- bd567e6

## More information
[Transferable interface](https://developer.mozilla.org/en-US/docs/Web/API/Transferable)
[Tests for PromiseWorker wrapper](https://github.com/jibrelnetwork/jwallet-web/blob/feature/workers/src/workers/PromiseWorker.test.js)

# EventEmitterWorker
### subscribe
*Creates subscription for worker*
#### Input
```
  worker: Object,
  {
    payload,
    transfer,
  }: EventEmitterWorkerEventPayload
```
#### Output
```
EventEmitter, that will push "error"/"data" events for correspond listeners
```
### unsubscribe
*Removes subscription for worker and terminate it*
#### Input
```
null
```
#### Output
```
null
```
## Example of usage
*worker.js*
```
self.onmessage = (msg) => {
  setInterval(() => {
    try {
      // process msg.data.payload

      self.postMessage({
        payload: 'some payload',
      })
    } catch (err) {
      self.postMessage({
        error: true,
        payload: {
          stack: err.stack,
          message: err.message,
        },
      })
    }
  }, ...)
}
```

*main.js*
```
import Worker from './worker.js'
import EventEmitterWorker from './EventEmitterWorker'

const worker = new Worker()
const eeWorker = new EventEmitterWorker()

const taskData = {
  payload: 'some payload that will be used inside worker to process task',
  transfer: 'optional array of Transferable objects to transfer ownership of (second argument of worker postMessage method)',
}

const ee = eeWorker.subscribe(worker, taskData)
ee.on('data', data => { /* handle event data */ })
ee.on('error', err => { /* handle event error */ })
```
## More information
[Events API](https://nodejs.org/api/events.html#events_emitter_off_eventname_listener)
[Tests for EventEmitterWorker wrapper](https://github.com/jibrelnetwork/jwallet-web/blob/feature/workers/src/workers/EventEmitterWorker.test.js)

### CODE REVIEW

**Comment by IViol** [comment]
New errors' API will be fixed a bit later

**Comment by IViol** [comment]
> New errors' API will be fixed a bit later

done

**Comment by stcherenkov** [comment]
Copy docs to https://github.com/jibrelnetwork/frontend, please?

**Comment by IViol** [comment]
> Copy docs to https://github.com/jibrelnetwork/frontend, please?

https://github.com/jibrelnetwork/frontend/pull/1

**Pull request merged**
